# Generated by Django 5.0.3 on 2024-04-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['surname', 'name'], 'verbose_name': 'список клиентов', 'verbose_name_plural': 'список клиентов'},
        ),
    ]
