# Generated by Django 5.0.3 on 2024-04-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pers_status',
            field=models.CharField(blank=True, choices=[('individual', 'Физлицо'), ('indiv_entrepr', 'Не подано')], default='individual', max_length=15, verbose_name='Статус физлица'),
        ),
    ]
