# Generated by Django 5.0.3 on 2024-04-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotListBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_efrsb_urls', models.URLField(help_text='Введите ссылку на ЕФРСБ', verbose_name='Ссылка на ЕФРСБ')),
                ('lot_place_urls', models.URLField(help_text='Введите ссылку на местоположение лота', verbose_name='Ссылка на местопровеления торга')),
                ('obligator', models.CharField(help_text='Имя должника', max_length=50, verbose_name='Должник')),
                ('proc_type', models.CharField(choices=[('auction', 'Аукцион'), ('public_offer', 'Публичное предложение')], max_length=20, verbose_name='Тип процедуры')),
                ('end_of_feed', models.DateField(verbose_name='Конец подачи заявки')),
                ('auction_day', models.DateField(verbose_name='Дата проведения аукциона')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена лота')),
                ('action_status', models.CharField(blank=True, choices=[('conducted', 'Проведены'), ('not_conducted', 'Не проведены')], max_length=15, null=True, verbose_name='Статус торгов')),
                ('feed_status', models.CharField(blank=True, choices=[('submitted', 'Подано'), ('not_submitted', 'Не подано')], max_length=13, null=True, verbose_name='Статус заявки')),
                ('feed_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена заявки')),
                ('price_procent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент за агентское вознаграждение')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Лот банка',
                'verbose_name_plural': 'Лоты банка',
            },
        ),
    ]
