# Generated by Django 5.0.3 on 2024-04-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotslist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotlistbank',
            options={'verbose_name': 'лоты', 'verbose_name_plural': 'Список лотов'},
        ),
    ]
