# Generated by Django 5.0.3 on 2024-04-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotslist', '0003_alter_lotlistbank_auction_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotlistbank',
            name='lot_number',
            field=models.CharField(default=1, max_length=40, verbose_name='введите номера лотов клиента через запятую'),
            preserve_default=False,
        ),
    ]
